### ISSUE TITLE
still in my head

### ISSUE THREAD

**Issue by C-o-m-o-n** [C-o-m-o-n/repoServe#1]
adding staff soon

**Comment by GautamTirumala** [comment]
I would love to know what's on your mind. Your plan and contribute to this project

**Comment by C-o-m-o-n** [comment]
I created the repository but I did not add anything then. I'm currently setting up the github authentication but I have initialized and deployed nextjs, you can check it out.
This is the idea:
To allow github devs to save some repos that they may have come across and are interested in but didn't have the time to check them out so that they might check them later.
Sorry I did not explain that earlier. I hope I have given you insight to contribute. I'll really appreciate it if you do.

Thanks
